require:
- rubocop

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false  

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let']

Metrics/MethodLength:
  Max: 15

Style/OneLineConditional:
  Enabled: false  
  
AllCops:
  SuggestExtensions: false
  NewCops: enable