require:
- rubocop

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: true

Metrics/AbcSize:
  Enabled: true 

Metrics/BlockLength:
  IgnoredMethods: ['describe']

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 100

Style/OneLineConditional:
  Enabled: false  
  
AllCops:
  SuggestExtensions: false
  NewCops: enable