#!/bin/bash
set -e
echo
echo '================ Instalando dependências... ================='
echo
bundle install
echo
echo '===================== Extraindo Dados... ====================='
ruby 'data/parse_population_data_script.rb'
echo
echo '==================== Testando o código... ===================='
echo
rspec
echo
echo '================== A aplicação está pronta ==================='
ruby 'nomes_brasil.rb'
