#!/bin/bash
set -e
echo
echo '================= Instalando dependências =================='
echo
bundle install
echo
echo '===================== Extraindo Dados... ====================='
echo
ruby 'start.rb'
