#!/bin/bash
set -e
echo
echo '================ Instalando dependências... ================='
echo
bundle install
echo
echo '==================== Testando o código... ===================='
echo
rspec
echo
echo '===================== Extraindo Dados... ====================='
echo
ruby 'start.rb'
