#!/bin/bash
set -e
echo
echo '================ Instalando dependências... ================='
echo
bundle install
echo
echo '==================== Testando o código... ===================='
echo
rspec
echo
echo '================== A aplicação está pronta ==================='
ruby 'nomes_brasil.rb'
